# A full list of materials can be found here: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html

# A list of items that will be protected from lava.
lava-guard:
  - DIAMOND
  - NETHER_STAR

# A list of items that will be protected from cactus.
cactus-guard:
  - DIAMOND
  - NETHER_STAR
